import type { ScanReport } from "./types.js";
const esc=(value:unknown)=>String(value??"尚未观察").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
export function scanHtml(report:ScanReport):string {
  const source=(id:string)=>report.sources.find(item=>item.id===id);
  const origin=(id:string)=>{const item=source(id);return item?`${item.client}/${item.scope} · ${item.path}`:"未知来源";};
  const finding=(item:ScanReport["findings"][number])=>`<article><h3>${esc(item.title)}</h3><p>${esc(item.code)} · ${esc(item.severity)} · ${esc(item.confidence)} · ${esc(item.evidenceKind)}</p><p>${esc(item.detail)}</p><p>下一步：${esc(item.nextStep)}</p><p class="muted">来源：${esc(item.sourceId?origin(item.sourceId):"未观察")} ${item.location?`· ${item.location.line}:${item.location.column}`:"· 节点位置未观察"}</p><details><summary>规则前提、版本、复查与反例</summary><p>前提：${esc(item.rule?.precondition)}</p><p>适用：${esc(item.rule?.applicableVersions.join("、"))} · ${esc(item.rule?.versionStatus)}</p><p>影响：${esc(item.rule?.impact)}</p><p>复查：${esc(item.rule?.recheck)}</p><p>反例：${esc(item.rule?.counterexample)}</p></details><small>发现编号 ${esc(item.id)}</small></article>`;
  const comparisons=report.comparisons.map(group=>`<article><h3>${esc(group.name)} · ${group.relation==="confirmed"?"用户已确认同一服务":"仅为候选，需确认映射"}</h3><p>${group.serverIds.map(id=>{const service=report.servers.find(item=>item.id===id);return esc(`${service?.client}: ${service?.name} (${id})`);}).join("<br>")}</p><p>不同字段：${esc(group.differingFields.join("、")||"已比较的入口字段一致")}</p><p>凭据关系：${esc(group.credentialRelation)}；差异可能有意，表达式不当成真实凭据。</p></article>`).join("");
  const servers=report.servers.map(server=>`<section id="service-${esc(server.id)}"><h2>${esc(server.name)} · ${esc(server.client)}</h2><p>服务编号 ${esc(server.id)} · ${esc(server.transport)} · 加载推断 ${esc(server.state)} · 启用 ${esc(server.enabled)}</p><p>解析执行文件：${esc(server.resolvedExecutable)}<br>参数：${server.argumentCount} 项，值隐藏<br>显式工作目录：${esc(server.cwd)}<br>端点：${esc(server.origin)}，路径和查询隐藏</p><h3>有效字段来源与覆盖链</h3><table><tr><th>字段</th><th>有效来源</th><th>节点</th><th>被覆盖来源</th></tr>${server.origins.map(field=>`<tr><td>${esc(field.field)}</td><td>${esc(origin(field.sourceId))}<br><code>${esc(JSON.stringify(field.keyPath))}</code></td><td>${esc(field.location?`${field.location.line}:${field.location.column} (offset ${field.location.offset})`:"未定位")}</td><td>${(field.overridden??[]).map(prior=>esc(origin(prior.sourceId))).join(" → ")||"无已知覆盖"}</td></tr>`).join("")}</table><p>整项被替代来源：${server.shadowedSources.map(id=>esc(origin(id))).join(" → ")||"无"}。Claude 覆盖整条服务，不继承低层未出现字段。</p><h3>此服务发现</h3>${report.findings.filter(item=>item.serverId===server.id).map(finding).join("")||"<p>没有规则命中；原生会话仍未验证。</p>"}</section>`).join("");
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>跨客户端配置诊断</title><style>body{font:16px/1.65 system-ui;max-width:1100px;margin:40px auto;padding:0 24px;background:#f5f7fb;color:#18253a}section,article{background:white;padding:20px;margin:16px 0;border:1px solid #dce3ef;border-radius:12px}h3{margin:0}small,.muted{color:#52647a}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid #dce3ef;overflow-wrap:anywhere}code{font-size:13px}</style><h1>跨客户端配置诊断</h1><p>${esc(report.createdAt)} · 只读文件证据 · 当前原生会话尚未验证</p><section><h2>入口与版本上下文</h2><p>工作区：${esc(report.context.workspace)}<br>诊断 cwd：${esc(report.context.workspace)}<br>位置：${esc(report.context.location)} · Profile：${esc(report.context.profile)} · 额外启动覆盖：${esc(report.context.launchOverrides)}</p>${report.observations.map(item=>`<p>${esc(item.client)} · 入口 ${esc(report.context.surfaces[item.client]??"unknown")} · 版本 ${esc(item.version)} · 执行入口 ${esc(item.executable)}</p>`).join("")}</section><h2>跨客户端服务差异</h2>${comparisons||"<p>没有已确认映射或同名候选；可使用 map 明确不同名称的同一服务。</p>"}${servers}<section><h2>读取范围及未加载来源</h2>${report.sources.map(item=>`<p>${esc(item.client)}/${esc(item.scope)} · ${esc(item.state)} · 纳入解释 ${esc(item.included)}<br>${esc(item.path)}</p>`).join("")}</section><h2>上下文与文件发现</h2>${report.findings.filter(item=>item.serverId===null).map(finding).join("")}<section><h2>网络来源（未主动连接）</h2>${(report.network??[]).map(item=>`<p>${esc(item.client)} · ${esc(item.target)} · 代理来源 ${esc(item.proxySource)} · 类型 ${esc(item.proxyKind)} · NO_PROXY 候选 ${esc(item.bypassCandidate)} · 证书 ${esc(item.certificate)}</p>`).join("")}</section><section>${report.notes.map(note=>`<p>${esc(note)}</p>`).join("")}</section></html>`;
}
